"""
Train the transaction failure-risk model.

Usage (from the backend/ directory, so the `app` package resolves):

    python -m app.ml.train

This is a standalone script -- no MongoDB, no FastAPI, no .env required.
It reads data/ml_training_dataset.csv (generated by app/ml/generate_dataset.py),
trains and compares three models, and persists the selected one as a single
scikit-learn Pipeline (preprocessing + model) to
app/ml/artifacts/failure_risk_model.joblib.

That artifact is what app/ml/model_loader.py loads at prediction time, and
what app/services/ml_service.py feeds a single-row DataFrame into via
pipeline.predict_proba(). The column names built in ml_service.py MUST match
FEATURE_COLUMNS below -- that coupling is intentional and documented there.

Design decisions (see the ML design review for the full discussion):
- Target: status == "failed" (binary). Rows with status == "pending" are
  excluded entirely -- their eventual outcome isn't known yet, so they are
  neither a positive nor a negative example for this classifier.
- Features are restricted to information available BEFORE a transaction's
  outcome is known: amount, hour, day_of_week, currency, transaction_type,
  payment_method, category, merchant_id. customer_id and raw created_at are
  excluded (see FEATURE_COLUMNS docstring below for why).
- Preprocessing (OneHotEncoder + StandardScaler) is fit ONLY on the training
  split and reused (not refit) on the test split, via scikit-learn's
  Pipeline -- this is what prevents preprocessing-side leakage.
- Because failures are a minority class (~12% here), accuracy is not a
  meaningful metric on its own -- a model that always predicts "successful"
  would already score ~88% accuracy while being useless. Precision, recall,
  F1, and ROC-AUC/PR-AUC are reported instead.
"""

import os

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# backend/app/ml/train.py -> repo root is three levels up (same as
# generate_dataset.py, which writes to this same path).
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
_DATASET_PATH = os.path.join(_REPO_ROOT, "data", "ml_training_dataset.csv")
_ARTIFACT_DIR = os.path.join(os.path.dirname(__file__), "artifacts")
_ARTIFACT_PATH = os.path.join(_ARTIFACT_DIR, "failure_risk_model.joblib")

# Numeric features: passed through StandardScaler.
# NOTE: hour and day_of_week are integers with a natural ordering, but they
# are cyclical (hour 23 is "close to" hour 0, not far from it). Scaling them
# as plain numeric features is a known simplification -- a more faithful
# encoding (sin/cos transform) is listed as a future improvement, not done
# here to keep the pipeline simple and explainable for this MVP.
NUMERIC_FEATURES = ["amount", "hour", "day_of_week"]

# Categorical features: passed through OneHotEncoder(handle_unknown="ignore")
# so a merchant_id/category/etc. not seen during training doesn't crash
# inference -- it's just encoded as all-zeros for that feature instead.
CATEGORICAL_FEATURES = ["currency", "transaction_type", "payment_method", "category", "merchant_id"]

FEATURE_COLUMNS = NUMERIC_FEATURES + CATEGORICAL_FEATURES

TARGET_COLUMN = "status"
POSITIVE_LABEL = "failed"

RANDOM_STATE = 42
TEST_SIZE = 0.2


def load_training_frame() -> pd.DataFrame:
    """
    Load the dataset and drop pending rows.

    Pending transactions are excluded because their outcome (will they
    eventually succeed or fail?) is not yet known -- including them as
    either class would inject incorrect labels into training.
    """
    df = pd.read_csv(_DATASET_PATH)
    df = df[df[TARGET_COLUMN] != "pending"].reset_index(drop=True)
    return df


def build_pipeline(model) -> Pipeline:
    """
    Wrap a classifier in a Pipeline with the shared preprocessing step.
    Using one Pipeline object (not separate encoder + model objects) means
    the exact same fitted preprocessing is always applied consistently at
    both training and inference time, and the whole thing serializes as a
    single joblib artifact.
    """
    preprocessor = ColumnTransformer(
        transformers=[
            ("numeric", StandardScaler(), NUMERIC_FEATURES),
            ("categorical", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
        ]
    )
    return Pipeline(steps=[("preprocess", preprocessor), ("model", model)])


def evaluate(pipeline: Pipeline, X_test: pd.DataFrame, y_test: pd.Series) -> dict:
    """
    Compute the metrics that actually matter for an imbalanced binary
    classification problem. Accuracy is deliberately NOT included as a
    headline metric -- see module docstring.
    """
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)[:, 1]

    return {
        "precision": precision_score(y_test, y_pred, pos_label=1, zero_division=0),
        "recall": recall_score(y_test, y_pred, pos_label=1, zero_division=0),
        "f1": f1_score(y_test, y_pred, pos_label=1, zero_division=0),
        "roc_auc": roc_auc_score(y_test, y_proba),
        "pr_auc": average_precision_score(y_test, y_proba),
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
    }


def _print_metrics(name: str, metrics: dict) -> None:
    print(f"--- {name} ---")
    print(f"  Precision : {metrics['precision']:.3f}")
    print(f"  Recall    : {metrics['recall']:.3f}")
    print(f"  F1        : {metrics['f1']:.3f}")
    print(f"  ROC-AUC   : {metrics['roc_auc']:.3f}")
    print(f"  PR-AUC    : {metrics['pr_auc']:.3f}")
    tn, fp, fn, tp = (
        metrics["confusion_matrix"][0][0],
        metrics["confusion_matrix"][0][1],
        metrics["confusion_matrix"][1][0],
        metrics["confusion_matrix"][1][1],
    )
    print(f"  Confusion matrix: TN={tn}  FP={fp}  FN={fn}  TP={tp}")
    print()


def main() -> None:
    df = load_training_frame()
    print(f"Loaded {len(df)} non-pending rows from {_DATASET_PATH}")

    y = (df[TARGET_COLUMN] == POSITIVE_LABEL).astype(int)
    X = df[FEATURE_COLUMNS]

    print(f"Failure rate in dataset: {y.mean():.2%}")
    print()

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
    )
    print(f"Train rows: {len(X_train)}  Test rows: {len(X_test)}")
    print(f"Train failure rate: {y_train.mean():.2%}  Test failure rate: {y_test.mean():.2%}")
    print()

    # --- Baseline: DummyClassifier ---
    # Predicts using only the label distribution, ignoring every feature.
    # Its job is to define the floor -- any real model that doesn't clearly
    # beat this baseline isn't actually learning anything useful from the
    # features. "stratified" (not "most_frequent") is used so the baseline
    # still attempts positive predictions sometimes, giving it a non-zero
    # (if low-quality) recall/precision to compare against.
    baseline = build_pipeline(DummyClassifier(strategy="stratified", random_state=RANDOM_STATE))
    baseline.fit(X_train, y_train)
    baseline_metrics = evaluate(baseline, X_test, y_test)
    _print_metrics("Baseline: DummyClassifier (stratified)", baseline_metrics)

    # --- Model 1: Logistic Regression ---
    # class_weight="balanced" re-weights the loss inversely proportional to
    # class frequency, which pushes the model to actually try to catch
    # minority-class (failed) examples rather than defaulting to always
    # predicting "successful" (which would already get ~88% accuracy here).
    # This trades precision for recall -- expected and desired for a
    # "flag for review" risk signal, where missing a real failure (false
    # negative) is treated as worse than a false alarm (false positive).
    logistic = build_pipeline(
        LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE)
    )
    logistic.fit(X_train, y_train)
    logistic_metrics = evaluate(logistic, X_test, y_test)
    _print_metrics("Model 1: Logistic Regression (class_weight=balanced)", logistic_metrics)

    # --- Model 2: Random Forest ---
    # Tests whether a non-linear model can find interaction effects (e.g.
    # "risky merchant AND late night" compounding) that logistic regression,
    # as a linear-in-the-features model, cannot represent directly.
    forest = build_pipeline(
        RandomForestClassifier(
            n_estimators=200,
            max_depth=6,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        )
    )
    forest.fit(X_train, y_train)
    forest_metrics = evaluate(forest, X_test, y_test)
    _print_metrics("Model 2: Random Forest (class_weight=balanced)", forest_metrics)

    candidates = {
        "logistic_regression": (logistic, logistic_metrics),
        "random_forest": (forest, forest_metrics),
    }

    # --- Model selection ---
    # Random Forest scores slightly higher on PR-AUC (0.239 vs 0.208) in
    # this run, but Logistic Regression is selected as the final model:
    #   - Its coefficients are directly interpretable (each feature's
    #     contribution to the failure score has a sign and magnitude that
    #     can be explained to a reviewer or a merchant), whereas the
    #     Random Forest's decision boundary cannot be summarized as simply.
    #   - For an MVP "flag for review" signal, explainability is treated as
    #     more valuable than a ~0.03 PR-AUC gain -- see the ML design
    #     review's discussion of explainability requirements.
    #   - The gap between the two models is small relative to the overall
    #     noise in this dataset (both hover around ROC-AUC 0.645), so the
    #     interpretability trade-off is not being made against a
    #     dramatically stronger alternative.
    # This is a documented judgment call, not a metric-maximizing choice --
    # re-run this script and inspect the printed metrics above if that
    # trade-off should be revisited.
    selected_name = "logistic_regression"
    selected_pipeline, selected_metrics = candidates[selected_name]

    print("=" * 60)
    print(f"SELECTED MODEL: {selected_name}")
    print(f"  (chosen for interpretability; PR-AUC={selected_metrics['pr_auc']:.3f} vs "
          f"random_forest's {forest_metrics['pr_auc']:.3f} -- see comment above)")
    print("=" * 60)
    print()

    os.makedirs(_ARTIFACT_DIR, exist_ok=True)
    joblib.dump(selected_pipeline, _ARTIFACT_PATH)
    print(f"Saved pipeline to {_ARTIFACT_PATH}")


if __name__ == "__main__":
    main()