from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class TransactionType(str, Enum):
    """Allowed values for transaction_type."""
    PAYMENT = "payment"
    REFUND = "refund"
    CHARGEBACK = "chargeback"
    EXPENSE = "expense"


class TransactionStatus(str, Enum):
    """Allowed values for status."""
    SUCCESSFUL = "successful"
    FAILED = "failed"
    PENDING = "pending"


class TransactionSource(str, Enum):
    """
    Where a transaction record came from. This exists purely to keep the
    dashboard's financial analytics honest: demo/synthetic data (used for
    local development and for generating ML training examples) must never
    be silently mixed into a report that's supposed to represent the
    user's actual uploaded statement.

    - MANUAL: created directly via POST /api/transactions (e.g. through
      Swagger, or any future real API consumer). Treated as real data.
    - SYNTHETIC_SEED: generated by app/utils/synthetic_data.py via
      POST /api/transactions/seed. Demo/test data only -- excluded from
      the analytics endpoints the dashboard reads from.
    - STATEMENT_IMPORT: parsed from an uploaded PhonePe/Paytm/GPay PDF
      statement (app/services/pdf_import_service.py). This is the user's
      real financial data.
    """
    MANUAL = "manual"
    SYNTHETIC_SEED = "synthetic_seed"
    STATEMENT_IMPORT = "statement_import"


class TransactionCreate(BaseModel):
    """
    Fields required from the client when creating a new transaction.
    transaction_id and created_at are generated by the server, not the client,
    so they are not part of this input model.
    """
    merchant_id: str
    amount: float = Field(gt=0, description="Transaction amount, must be positive")
    currency: str = Field(min_length=3, max_length=3, description="3-letter currency code, e.g. USD")
    transaction_type: TransactionType
    status: TransactionStatus
    payment_method: str
    customer_id: str
    category: str


class Transaction(TransactionCreate):
    """
    Full transaction record as stored in MongoDB and returned to clients.
    Adds the server-generated fields on top of TransactionCreate.
    """
    transaction_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    # Server-controlled, like transaction_id/created_at -- deliberately NOT
    # on TransactionCreate, so a client can never claim its own transaction
    # is a "statement_import". Defaults to MANUAL so:
    #   (a) existing MongoDB documents from before this field existed are
    #       read back as MANUAL (via this same default), not silently
    #       dropped or misclassified as demo data, and
    #   (b) real transactions created through POST /api/transactions keep
    #       working exactly as before, with no client-side change required.
    source: TransactionSource = Field(default=TransactionSource.MANUAL)