from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class TransactionType(str, Enum):
    """Allowed values for transaction_type."""
    PAYMENT = "payment"
    REFUND = "refund"
    CHARGEBACK = "chargeback"
    EXPENSE = "expense"


class TransactionStatus(str, Enum):
    """Allowed values for status."""
    SUCCESSFUL = "successful"
    FAILED = "failed"
    PENDING = "pending"


class TransactionCreate(BaseModel):
    """
    Fields required from the client when creating a new transaction.
    transaction_id and created_at are generated by the server, not the client,
    so they are not part of this input model.
    """
    merchant_id: str
    amount: float = Field(gt=0, description="Transaction amount, must be positive")
    currency: str = Field(min_length=3, max_length=3, description="3-letter currency code, e.g. USD")
    transaction_type: TransactionType
    status: TransactionStatus
    payment_method: str
    customer_id: str
    category: str


class Transaction(TransactionCreate):
    """
    Full transaction record as stored in MongoDB and returned to clients.
    Adds the server-generated fields on top of TransactionCreate.
    """
    transaction_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))